---
# https://github.com/orgs/open-webui/packages/container/package/open-webui

services:
  webui:
    image: ghcr.io/open-webui/open-webui:${DOCKER_TAG:-main}
    container_name: webui
    privileged: false
    restart: unless-stopped
    volumes:
    - ./data:/app/backend/data
    ports:
    - ${SERV_PORT:-8080}:8080
