---
services:
  backend:
    image: ghcr.io/hedgedoc/hedgedoc/backend:develop
    ports:
    - ${BACKEND_PORT:-3000}:3000
    volumes:
    - ./backend.env:/usr/src/app/backend/.env
    - ./data/uploads:/usr/src/app/backend/uploads

  frontend:
    image: ghcr.io/hedgedoc/hedgedoc/frontend:develop
    ports:
    - ${FRONTEND_PORT:-3001}:3001

  db:
    image: postgres:16
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
