---
# https://github.com/gshang2017/docker/tree/master/qBittorrent

services:
  qbittorrent:
    image: johngong/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${QB_WEBUI_PORT}:${QB_WEBUI_PORT}
    - ${QB_BT_PORT}:6881
    - ${QB_BT_PORT}:6881/udp
    volumes:
    - /srv/qbittorrent/config:/config
    - /srv/qbittorrent/downloads:/Downloads
