---
# https://github.com/gshang2017/docker/tree/master/qBittorrent

services:
  qbittorrent:
    image: johngong/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
    - ${QB_WEBUI_PORT:-8989}:${QB_WEBUI_PORT:-8989}
    - ${QB_BT_PORT:-6881}:6881
    - ${QB_BT_PORT:-6881}/udp:6881/udp
    volumes:
    - /srv/qbittorrent/config:/config
    - /srv/qbittorrent/downloads:/Downloads
