---
# https://hub.docker.com/r/lbjlaq/antigravity-manager
services:
  antigravity-manager:
    container_name: antigravity-manager
    env_file:
      - path: ./.env
        required: false
    hostname: antigravity-manager
    image: lbjlaq/antigravity-manager:latest
    ports:
      - 8045:8045
    restart: unless-stopped
