---
# https://www.wiz.cn/docker.html
version : '3'

services:
  wiz:
    image: wiznote/wizserver:latest
    container_name: wiz
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./storage:/wiz/storage
    ports:
    - ${WEB_PORT}:80
    - ${SERV_PORT}:9269/tcp
    - ${SERV_PORT}:9269/udp
