services:
  emqx:
    ports: !override
      - ${TCP_PORT:-1883}:1883
      - ${SSL_PORT:-8883}:8883
      - ${WS_PORT:-8083}:8083
      - ${WSS_PORT:-8084}:8084
      - ${HTTP_PORT:-18083}:18083
      - ${HTTPS_PORT:-18084}:18084
    volumes:
      - ./data/data:/opt/emqx/data
      - ./data/log:/opt/emqx/log
    # - /srv/acme/ssl/emqx.io.key:/etc/emqx/certs/emqx.key
    # - /srv/acme/ssl/emqx.io.fullchain.cer:/etc/emqx/certs/emqx.cer
