---
# https://github.com/emqx/emqx

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
    - ${MQTT_PORT:-1883}:1883
    - ${WS_PORT:-8083}:8083
    - ${HTTP_PORT:-8084}:8084
    - ${MQTTS_PORT:-8883}:8883
    - ${DASH_PORT:-18083}:18083
    volumes:
    - ./data/data:/opt/emqx/data
    - ./data/log:/opt/emqx/log
