---
# https://github.com/emqx/emqx
version : '3'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - 1883:1883
    - 8083:8083
    - 8084:8084
    - 8883:8883
    - 18083:18083
