---
# http://hub.docker.com/r/joplin/server

services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    restart: unless-stopped
    depends_on:
    - postgres
    ports:
    - ${SERV_PORT:-22300}:22300

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
    - ${POSTGRES_PORT:-5432}:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
