---
# https://github.com/laurent22/joplin/tree/dev/packages/server
version : '3'

services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    restart: unless-stopped
    env_file:
    - ./.env
    depends_on:
    - postgres
    ports:
    - ${SERV_PORT}:22300

    postgres:
      image: postgres:15
      restart: unless-stopped
      env_file:
      - ./.env
      ports:
      - ${POSTGRES_PORT}:5432
      volumes:
      - ./postgres:/var/lib/postgresql/data
