dir=/data

# --- HTTP/FTP/SFTP ---
max-connection-per-server=16

# --- RPC Server (For Web UIs) ---
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-secret=YOUR_SECRET_TOKEN
