---
# https://ghcr.io/jetsung/aria2
services:
  aria2:
    container_name: aria2
    env_file:
      - path: ./.env
        required: false
    hostname: aria2
    image: ghcr.io/jetsung/aria2:latest
    ports:
      - 6800:6800
    restart: unless-stopped
