---
# https://hub.docker.com/r/jetsung/relaydrop
services:
  relaydrop:
    container_name: relaydrop
    env_file:
      - path: ./.env
        required: false
    image: jetsung/relaydrop:latest
    ports:
      - 9090:9090
    restart: unless-stopped
