---
# https://github.com/harness/drone

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    restart: unless-stopped
    volumes:
    - ./data:/data
    env_file:
    - ./.env
    ports:
    - ${HTTP_PORT}:80
    - ${HTTPS_PORT}:443

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: unless-stopped
    env_file:
    - ./.env
    depends_on:
    - drone-server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
