services:
  app:
    hostname: listmonk
    env_file:
      - path: ./.env
        required: false
    environment:
      TZ: ${TZ:-Asia/Shanghai}
    ports: !override
      - ${SERV_PORT:-9000}:9000
    volumes: !override
      - ./data/uploads:/listmonk/uploads:rw
    networks: !reset null
  db:
    env_file:
      - path: ./.env
        required: false
    ports: !reset []
    networks: !reset null
