---
version : '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${SWAGGER_PORT}:8080
    volumes:
    - ./conf:/app
