---
# https://hub.docker.com/r/vaultwarden/server

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-80}:80
    volumes:
    - /srv/vaultwarden:/data
