---
# https://github.com/ekzhang/rustpad

services:
  rustpad:
    image: ghcr.io/forkdo/rustpad:latest
    container_name: rustpad
    restart: unless-stopped
    volumes:
    - ./data:/app
    ports:
    - ${SERV_PORT:-3030}:3030
