services:
  gitea:
    ports: !override
      - ${GITEA_HTTP_PORT:-3000}:3000
      - ${GITEA_SSL_PORT:-22}:22
    volumes:
      - ./data/gitea:/data
      - ./data/.ssh:/data/git/.ssh

  runner:
    volumes:
      - ./data/runner:/data
      - ./data/postgres:/var/lib/postgresql

  db:
    volumes:
      - ./data/postgres:/var/lib/postgresql
