---

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
    - ${GITEA_HTTP_PORT:-3000}:3000
    - ${GITEA_SSL_PORT:-22}:22
    volumes:
    - ./gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    depends_on:
    - db

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
    - ./postgres:/var/lib/postgresql/data
