---
version : '3'

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${GITEA_HTTP_PORT}:3000
    - ${GITEA_SSL_PORT}:22
    volumes:
    - ./gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    depends_on:
    - db

  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./postgres:/var/lib/postgresql/data
