---
version : '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${WEB_HTTP_PORT}:80
    - ${WEB_HTTPS_PORT}:443
    volumes:
    - .:/var/www:cached
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/nginx/ssl
    command: nginx
