---
version : '3'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${WEB_HTTP_PORT}:80
    - ${WEB_HTTPS_PORT}:443
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
