---

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${HTTP_PORT:-80}:80
    - ${HTTPS_PORT:-443}:443
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
