---

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${HTTP_PORT:-80}:80
    - ${HTTPS_PORT:-443}:443
    volumes:
    - .:/var/www:cached
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/nginx/ssl
    command: nginx
