---
# https://hub.docker.com/r/schollz/croc

services:
  croc:
    image: schollz/croc:latest
    container_name: croc
    restart: unless-stopped
    ports:
    - 9009-9013:9009-9013
    command: [relay]
