---
services:
  forgejo:
    ports: !override
      - ${GIT_HTTP_PORT:-3000}:3000
      - ${GIT_SSL_PORT:-22}:22
    volumes:
      - ./data/forgejo:/data
      - ./data/.ssh:/data/git/.ssh

  runner:
    volumes:
      - ./data/runner:/data
      # - ./runner-token:/runner-token

  db:
    volumes:
      - ./data/postgres:/var/lib/postgresql
