---
# https://hub.docker.com/r/dpage/pgadmin4/
services:
  pgadmin:
    container_name: pgadmin
    env_file:
      - path: ./.env
        required: false
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 80:80
    restart: unless-stopped
