---
# https://hub.docker.com/r/dpage/pgadmin4/

services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${PGADMIN_PORT}:80
