---
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    hostname: gitlab
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
      - ${HTTPS_PORT:-443}:443
      - ${SSH_PORT:-22}:22
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password

  gitlab-runner:
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/runner:/etc/gitlab-runner

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt
