---
# https://github.com/minio/minio/tree/master/docs/orchestration/docker-compose
version : '3'

services:
  minio:
    image: quay.io/minio/minio:${MINIO_IMAGE_VERSION}
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    env_file: ./.env
    healthcheck:
      test: [CMD, curl, -f, http://localhost:9000/minio/health/live]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
    - /srv/minio:/data
    ports:
    - ${MINIO_SERVER_PORT}:9000
    - ${MINIO_CONSOLE_PORT}:9001
