---
# https://github.com/asciinema/asciinema-server
# https://ghcr.io/asciinema/asciinema-server
#
# 服务全部 Docker
#

services:
  asciinema:
    image: ghcr.io/asciinema/asciinema-server:latest
    container_name: asciinema
    env_file:
    - ./.env
    volumes:
    - asciinema_data:/var/opt/asciinema
    ports:
    - $SERV_PORT:4000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: docker.io/library/postgres:16
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 2s
      timeout: 5s
      retries: 10
volumes :
  asciinema_data:
  postgres_data:
