---
# https://github.com/boypt/simple-torrent

services:
  cloud-torrent:
    image: boypt/cloud-torrent:latest
    container_name: cloud-torrent
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-3000}:3000
    volumes:
    - ./downloads:/downloads
    - ./torrents:/torrents
