---
# https://hub.docker.com/r/jpillora/cloud-torrent

services:
  cloud-torrent:
    image: jpillora/cloud-torrent:latest
    container_name: cloud-torrent
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-3000}:3000
    volumes:
    - ./downloads:/downloads
    - ./torrents:/torrents
