---
# https://hub.docker.com/r/bytemark/webdav

services:
  webdav:
    image: bytemark/webdav:latest
    container_name: webdav
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-80}:80
    volumes:
    - ./data:/var/lib/dav
