---
# https://github.com/BytemarkHosting/docker-webdav

services:
  webdav:
    image: bytemark/webdav:latest
    container_name: webdav
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-80}:80
    volumes:
    - ./data:/var/lib/dav
