---
# https://docs.gitlab.com/runner/install/docker.html

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
    - ./data:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
    # - /run/user/1001/docker.sock:/var/run/docker.sock
