---
# https://github.com/hightman/xunsearch

services:
  xunsearch:
    image: hightman/xunsearch:latest
    container_name: xunsearch
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-8383}:8383
    - ${SERV_PORT_1:-8384}:8384
    volumes:
    - ./data:/usr/local/xunsearch/data
