---
# https://github.com/etcd-io/etcd
version : '3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.6
    container_name: etcd
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./data:/etcd-data
    ports:
    - ${SERV_PORT_1}:2379
    - ${SERV_PORT_2}:2380
