---
services:
  remark:
    image: umputun/remark42:latest
    container_name: remark42
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./data:/srv/var
    ports:
    - ${SERV_PORT}:8080

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
