---
# https://hub.docker.com/_/mariadb

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
    - ${MARIADB_PORT:-3306}:3306
    volumes:
    - ./data:/var/lib/mysql
