---
# https://hub.docker.com/r/jellyfin/jellyfin
services:
  jellyfin:
    container_name: jellyfin
    env_file:
      - path: ./.env
        required: false
    hostname: jellyfin
    image: jellyfin/jellyfin:latest
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    restart: unless-stopped
