---
# https://hub.docker.com/r/messense/aliyundrive-webdav

services:
  webdav:
    image: messense/aliyundrive-webdav:latest
    container_name: aliyundrive-webdav
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-8080}:8080
