---
# https://hub.docker.com/_/mysql

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
    - ./data:/var/lib/mysql
    ports:
    - ${MYSQL_PORT:-3306}:3306
