---
version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./data:/var/lib/mysql
    ports:
    - ${MYSQL_PORT}:3306
