---
# https://quay.io/coreos/etcd

x-etcd-common: &etcd-common
  image: quay.io/coreos/etcd:v3.5.6
  restart: unless-stopped
  networks:
  - etcd-net
  volumes:
  - /etc/localtime:/etc/localtime

services     :
  etcd1:
    <<: *etcd-common
    container_name: etcd1
    ports:
    - 20000:2379
    - 20001:2380
    environment:
    - ALLOW_NONE_AUTHENTICATION=yes
    - ETCD_NAME=etcd1
    - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
    - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
    - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
    - ETCD_INITIAL_CLUSTER_STATE=new
    - ETCDCTL_API=3

  etcd2:
    <<: *etcd-common
    container_name: etcd2
    ports:
    - 20002:2379
    - 20003:2380
    environment:
    - ALLOW_NONE_AUTHENTICATION=yes
    - ETCD_NAME=etcd2
    - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
    - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
    - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
    - ETCD_INITIAL_CLUSTER_STATE=new
    - ETCDCTL_API=3

  etcd3:
    <<: *etcd-common
    container_name: etcd3
    ports:
    - 20004:2379
    - 20005:2380
    environment:
    - ALLOW_NONE_AUTHENTICATION=yes
    - ETCD_NAME=etcd3
    - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
    - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
    - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
    - ETCD_INITIAL_CLUSTER_STATE=new
    - ETCDCTL_API=3

networks     :
  etcd-net:
    driver: bridge
