---
# https://github.com/idevsig/filetas
services:
  filetas:
    image: idevsig/filetas:latest
    container_name: filetas
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - ${SERV_PORT}:8000
