volumes:
  ollama:
services:
  ollama:
    ports: !override
      - ${SERV_PORT:-11434}:11434
    volumes:
      - ./data:/root/.ollama
  rocm:
    ports: !override
      - ${SERV_PORT:-11434}:11434
    volumes:
      - ./data:/root/.ollama
