---
# https://github.com/valeriansaliou/sonic

services:
  sonic:
    image: valeriansaliou/sonic:latest
    container_name: sonic
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./config.cfg:/etc/sonic.cfg
    - /srv/sonic/store/:/var/lib/sonic/store/
    ports:
    - ${SERV_PORT}:1491
