---
# https://hub.docker.com/r/tickstep/aliyunpan-webdav

services:
  webdav:
    image: tickstep/aliyunpan-webdav:v0.1.5
    container_name: aliyunpan-webdav
    restart: unless-stopped
    ports:
    - ${SERV_PORT:-23077}:23077
