---
# https://hub.docker.com/r/tickstep/aliyunpan-webdav
version : '3'

services:
  webdav:
    image: tickstep/aliyunpan-webdav:v0.1.5
    container_name: aliyunpan-webdav
    restart: unless-stopped
    env_file:
    - ./.env
    ports:
    - ${SERV_PORT}:23077
