services:
  mail-server:
    ports: !override
      - ${HTTP_PORT:-8080}:8080
      - ${HTTPS_PORT:-443}:443
      - ${SMTP_PORT:-25}:25
      - ${SMTPSSL_PORT:-465}:465
      - ${SMTPTLS_PORT:-587}:587
      - ${IMAP_PORT:-143}:143
      - ${IMAPS_PORT:-993}:993
      - ${POP3_PORT:-110}:110
      - ${POP3S_PORT:-995}:995
