---
services:
  mail-server:
    image: stalwartlabs/mail-server:latest
    container_name: stalwart-mail
    tty: true
    stdin_open: true
    volumes:
    - ./data:/opt/stalwart-mail
    - /opt/stalwart-mail/webadmin.zip:/tmp/webadmin.zip
    network_mode: host
