---
# https://github.com/mindoc-org/mindoc/blob/master/docker-compose.yml

services:
  mindoc:
    image: registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1-beta.6
    container_name: mindoc
    privileged: false
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./mindoc:/mindoc-sync-host
    ports:
    - ${SERV_PORT:-8181}:8181
    dns:
    - 223.5.5.5
    - 223.6.6.6
