---
# http://hub.docker.com/r/getmeili/meilisearch

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    volumes:
    - ./data:/meili_data
    ports:
    - ${SERV_PORT:-7700}:7700
