---
# https://hub.docker.com/_/redis
# https://github.com/redis/docker-library-redis

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
    - ./data:/data
    ports:
    - ${SERV_PORT:-6379}:6379
