---
# https://hub.docker.com/_/redis
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    env_file:
    - ./.env
    volumes:
    - ./data:/data
    ports:
    - ${REDIS_PORT}:6379
